# Generated by Django 5.2.4 on 2025-09-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='poster',
        ),
    ]
